package msg

//defines all the constants and types for uaf
const (
	FIDO_VERSION = "v1.0"

	//Key Protection Types
	KEY_PROTECTION_SOFTWARE       = 0x01
	KEY_PROTECTION_HARDWARE       = 0x02
	KEY_PROTECTION_TEE            = 0x04
	KEY_PROTECTION_SECURE_ELEMENT = 0x08
	KEY_PROTECTION_REMOTE_HANDLE  = 0x10

	//User Verification Methods
	USER_VERIFY_PRESENCE    = 0x01
	USER_VERIFY_FINGERPRINT = 0x02
	USER_VERIFY_PASSCODE    = 0x04
	USER_VERIFY_VOICEPRINT  = 0x08
	USER_VERIFY_FACEPRINT   = 0x10
	USER_VERIFY_LOCATION    = 0x20
	USER_VERIFY_EYEPRINT    = 0x40
	USER_VERIFY_PATTERN     = 0x80
	USER_VERIFY_HANDPRINT   = 0x100
	USER_VERIFY_NONE        = 0x200
	USER_VERIFY_ALL         = 0x400

	//Matcher Protection Types
	MATCHER_PROTECTION_SOFTWARE = 0x01
	MATCHER_PROTECTION_TEE      = 0x02
	MATCHER_PROTECTION_ON_CHIP  = 0x04

	//Authenticator Attachment Hints
	ATTACHMENT_HINT_INTERNAL    = 0x01
	ATTACHMENT_HINT_EXTERNAL    = 0x02
	ATTACHMENT_HINT_WIRED       = 0x04
	ATTACHMENT_HINT_WIRELESS    = 0x08
	ATTACHMENT_HINT_NFC         = 0x10
	ATTACHMENT_HINT_BLUETOOTH   = 0x20
	ATTACHMENT_HINT_NETWORK     = 0x40
	ATTACHMENT_HINT_READY       = 0x80
	ATTACHMENT_HINT_WIFI_DIRECT = 0x100

	//Transaction Confirmation Display Types
	TRANSACTION_CONFIRMATION_DISPLAY_ANY                 = 0x01
	TRANSACTION_CONFIRMATION_DISPLAY_PRIVILEGED_SOFTWARE = 0x02
	TRANSACTION_CONFIRMATION_DISPLAY_TEE                 = 0x04
	TRANSACTION_CONFIRMATION_DISPLAY_HARDWARE            = 0x08
	TRANSACTION_CONFIRMATION_DISPLAY_REMOTE              = 0x10

	//Tags used for crypto algorithms and types
	UAF_ALG_SIGN_SECP256R1_ECDSA_SHA256_RAW = 0x01
	UAF_ALG_SIGN_SECP256R1_ECDSA_SHA256_DER = 0x02
	UAF_ALG_SIGN_RSASSA_PSS_SHA256_RAW      = 0x03
	UAF_ALG_SIGN_RSASSA_PSS_SHA256_DER      = 0x04
	UAF_ALG_SIGN_SECP256K1_ECDSA_SHA256_RAW = 0x05
	UAF_ALG_SIGN_SECP256K1_ECDSA_SHA256_DER = 0x06

	//Public Key Representation Formats
	UAF_ALG_KEY_ECC_X962_RAW     = 0x100
	UAF_ALG_KEY_ECC_X962_DER     = 0x101
	UAF_ALG_KEY_RSA_2048_PSS_RAW = 0x102
	UAF_ALG_KEY_RSA_2048_PSS_DER = 0x103

	//Predefined Tags
	TAG_UAFV1_REG_ASSERTION         = 0x3E01
	TAG_UAFV1_AUTH_ASSERTION        = 0x3E02
	TAG_UAFV1_KRD                   = 0x3E03
	TAG_UAFV1_SIGNED_DATA           = 0x3E04
	TAG_ATTESTATION_CERT            = 0x2E05
	TAG_SIGNATURE                   = 0x2E06
	TAG_ATTESTATION_BASIC_FULL      = 0x3E07
	TAG_ATTESTATION_BASIC_SURROGATE = 0x3E08
	TAG_KEYID                       = 0x2E09
	TAG_FINAL_CHALLENGE             = 0x2E0A
	TAG_AAID                        = 0x2E0B
	TAG_PUB_KEY                     = 0x2E0C
	TAG_COUNTERS                    = 0x2E0D
	TAG_ASSERTION_INFO              = 0x2E0E
	TAG_AUTHENTICATOR_NONCE         = 0x2E0F
	TAG_TRANSACTION_CONTENT_HASH    = 0x2E10
	TAG_EXTENSION                   = 0x3E11
	TAG_EXTENSION_2                 = 0x3E12
	TAG_EXTENSION_ID                = 0x2E13
	TAG_EXTENSION_DATA              = 0x2E14
)

type DOMString string

type Operation DOMString

type AAID DOMString

type KeyID DOMString

type ServerChallenge DOMString

type VerificationMethodANDCombinations []VerificationMethodDescriptor
